### ISSUE TITLE
`OSError: Could not find/load shared object file: libllvmlite.so` from broken conda-forge package.  Found fix with using numba channel.

### ISSUE THREAD

**Issue by jolespin** [apcamargo/genomad#10]
I'm getting the following error when installing genomad in a fresh environment: 

```
OSError: Could not find/load shared object file: libllvmlite.so
 Error was: libstdc++.so.6: failed to map segment from shared object
```

A couple of things I've tried but it was the same situation: 

 *  Reinstalling https://anaconda.org/conda-forge/llvmlite . 
 * Downgrading to v1.3.2 and v1.3.1

What ended up working was swapping the `llvmlite` install from `conda-forge` to `numba`

Here's the log:
```
(base) [jespinoz@login02 jcl110]$ mamba create -n genomad_env -c bioconda genomad

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.2.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['genomad']

bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
pkgs/r/linux-64                                               No change
pkgs/main/linux-64                                            No change
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
jolespin/linux-64                                             No change
qiime2/noarch                                                 No change
jolespin/noarch                                               No change
qiime2/linux-64                                               No change
Transaction

  Prefix: /expanse/projects/jcl110/anaconda3/envs/genomad_env

  Updating specs:

   - genomad


  Package                         Version  Build                    Channel                    Size
─────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                     0.1  conda_forge              conda-forge/linux-64     Cached
  + _openmp_mutex                     4.5  2_gnu                    conda-forge/linux-64     Cached
  + _py-xgboost-mutex                 2.0  cpu_0                    conda-forge/linux-64        8kB
  + absl-py                         1.4.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + aiohttp                         3.8.3  py310h5764c6d_1          conda-forge/linux-64     Cached
  + aiosignal                       1.3.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + appdirs                         1.4.4  pyh9f0ad1d_0             conda-forge/noarch       Cached
  + aragorn                        1.2.41  hec16e2b_0               bioconda/linux-64        Cached
  + aria2                          1.23.0  0                        bioconda/linux-64          29MB
  + astunparse                      1.6.3  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + async-timeout                   4.0.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + attrs                          22.2.0  pyh71513ae_0             conda-forge/noarch       Cached
  + blinker                           1.5  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + brotlipy                        0.7.0  py310h5764c6d_1005       conda-forge/linux-64     Cached
  + bzip2                           1.0.8  h7f98852_4               conda-forge/linux-64     Cached
  + c-ares                         1.18.1  h7f98852_0               conda-forge/linux-64     Cached
  + ca-certificates             2022.12.7  ha878542_0               conda-forge/linux-64     Cached
  + cached-property                 1.5.2  hd8ed1ab_1               conda-forge/noarch          4kB
  + cached_property                 1.5.2  pyha770c72_1             conda-forge/noarch       Cached
  + cachetools                      5.3.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + certifi                     2022.12.7  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + cffi                           1.15.1  py310h255011f_3          conda-forge/linux-64     Cached
  + charset-normalizer              2.1.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + click                           8.1.3  unix_pyhd8ed1ab_2        conda-forge/noarch       Cached
  + cryptography                   39.0.0  py310h34c0648_0          conda-forge/linux-64     Cached
  + flatbuffers                  22.12.06  hcb278e6_2               conda-forge/linux-64     Cached
  + frozenlist                      1.3.3  py310h5764c6d_0          conda-forge/linux-64     Cached
  + gast                            0.4.0  pyh9f0ad1d_0             conda-forge/noarch       Cached
  + gawk                            5.1.0  h7f98852_0               conda-forge/linux-64     Cached
  + genomad                         1.3.3  pyhdfd78af_0             bioconda/noarch          Cached
  + gettext                        0.21.1  h27087fc_0               conda-forge/linux-64     Cached
  + giflib                          5.2.1  h36c2ea0_2               conda-forge/linux-64     Cached
  + google-auth                    2.16.0  pyh1a96a4e_1             conda-forge/noarch       Cached
  + google-auth-oauthlib            0.4.6  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + google-pasta                    0.2.0  pyh8c360ce_0             conda-forge/noarch       Cached
  + grpcio                         1.51.1  py310h4a5735c_1          conda-forge/linux-64     Cached
  + h5py                            3.8.0  nompi_py310h0311031_100  conda-forge/linux-64     Cached
  + hdf5                           1.12.2  nompi_h4df4325_101       conda-forge/linux-64     Cached
  + icu                              70.1  h27087fc_0               conda-forge/linux-64     Cached
  + idna                              3.4  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + importlib-metadata              6.0.0  pyha770c72_0             conda-forge/noarch       Cached
  + joblib                          1.2.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + jpeg                               9e  h166bdaf_2               conda-forge/linux-64     Cached
  + keras                          2.11.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + keras-preprocessing             1.1.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + keyutils                        1.6.1  h166bdaf_0               conda-forge/linux-64     Cached
  + krb5                           1.20.1  h81ceb04_0               conda-forge/linux-64     Cached
  + ld_impl_linux-64                 2.40  h41732ed_0               conda-forge/linux-64     Cached
  + libabseil                  20220623.0  cxx17_h05df665_6         conda-forge/linux-64     Cached
  + libaec                          1.0.6  hcb278e6_1               conda-forge/linux-64     Cached
  + libblas                         3.9.0  16_linux64_openblas      conda-forge/linux-64     Cached
  + libcblas                        3.9.0  16_linux64_openblas      conda-forge/linux-64     Cached
  + libcurl                        7.87.0  hdc1c0ab_0               conda-forge/linux-64     Cached
  + libedit                  3.1.20191231  he28a2e2_2               conda-forge/linux-64     Cached
  + libev                            4.33  h516909a_1               conda-forge/linux-64     Cached
  + libffi                          3.4.2  h7f98852_5               conda-forge/linux-64     Cached
  + libgcc                          7.2.0  h69d50b8_2               conda-forge/linux-64     Cached
  + libgcc-ng                      12.2.0  h65d4601_19              conda-forge/linux-64     Cached
  + libgfortran-ng                 12.2.0  h69a702a_19              conda-forge/linux-64     Cached
  + libgfortran5                   12.2.0  h337968e_19              conda-forge/linux-64     Cached
  + libgomp                        12.2.0  h65d4601_19              conda-forge/linux-64     Cached
  + libgrpc                        1.51.1  h4fad500_1               conda-forge/linux-64     Cached
  + libiconv                         1.17  h166bdaf_0               conda-forge/linux-64     Cached
  + libidn2                         2.3.4  h166bdaf_0               conda-forge/linux-64     Cached
  + liblapack                       3.9.0  16_linux64_openblas      conda-forge/linux-64     Cached
  + libllvm11                      11.1.0  he0ac6c6_5               conda-forge/linux-64     Cached
  + libnghttp2                     1.51.0  hff17c54_0               conda-forge/linux-64     Cached
  + libnsl                          2.0.0  h7f98852_0               conda-forge/linux-64     Cached
  + libopenblas                    0.3.21  pthreads_h78a6416_3      conda-forge/linux-64     Cached
  + libpng                         1.6.39  h753d276_0               conda-forge/linux-64     Cached
  + libprotobuf                   3.21.12  h3eb15da_0               conda-forge/linux-64     Cached
  + libsqlite                      3.40.0  h753d276_0               conda-forge/linux-64     Cached
  + libssh2                        1.10.0  hf14f497_3               conda-forge/linux-64     Cached
  + libstdcxx-ng                   12.2.0  h46fd767_19              conda-forge/linux-64     Cached
  + libunistring                   0.9.10  h7f98852_0               conda-forge/linux-64     Cached
  + libuuid                        2.32.1  h7f98852_1000            conda-forge/linux-64     Cached
  + libxgboost                      1.7.1  cpu_ha3b9936_0           conda-forge/linux-64     Cached
  + libxml2                        2.10.3  h7463322_0               conda-forge/linux-64     Cached
  + libzlib                        1.2.13  h166bdaf_4               conda-forge/linux-64     Cached
  + llvmlite                       0.39.1  py310h58363a5_1          conda-forge/linux-64     Cached
  + markdown                        3.4.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + markdown-it-py                  2.1.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + markupsafe                      2.1.2  py310h1fa729e_0          conda-forge/linux-64     Cached
  + mdurl                           0.1.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + mmseqs2                      14.7e284  pl5321hf1761c0_0         bioconda/linux-64        Cached
  + multidict                       6.0.4  py310h1fa729e_0          conda-forge/linux-64     Cached
  + ncurses                           6.3  h27087fc_1               conda-forge/linux-64     Cached
  + numba                          0.56.4  py310ha5257ce_0          conda-forge/linux-64     Cached
  + numpy                          1.23.5  py310h53a5b5f_0          conda-forge/linux-64     Cached
  + oauthlib                        3.2.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + openssl                         3.0.7  h0b41bf4_2               conda-forge/linux-64     Cached
  + opt_einsum                      3.3.0  pyhd8ed1ab_1             conda-forge/noarch       Cached
  + packaging                        23.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + perl                           5.32.1  2_h7f98852_perl5         conda-forge/linux-64     Cached
  + pip                              23.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pooch                           1.6.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + prodigal-gv                    2.10.0  h7132678_0               bioconda/linux-64        Cached
  + protobuf                      4.21.12  py310heca2aa9_0          conda-forge/linux-64     Cached
  + py-xgboost                      1.7.1  cpu_py310hd1aba9c_0      conda-forge/linux-64     Cached
  + pyasn1                          0.4.8  py_0                     conda-forge/noarch       Cached
  + pyasn1-modules                  0.2.7  py_0                     conda-forge/noarch       Cached
  + pycparser                        2.21  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pygments                       2.14.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pyjwt                           2.6.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pyopenssl                      23.0.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pysocks                         1.7.1  pyha2e5f31_6             conda-forge/noarch       Cached
  + python                         3.10.8  h4a9ceb5_0_cpython       conda-forge/linux-64     Cached
  + python-crfsuite                 0.9.8  py310hbf28c38_1          conda-forge/linux-64     Cached
  + python-flatbuffers            23.1.21  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + python_abi                       3.10  3_cp310                  conda-forge/linux-64     Cached
  + pyu2f                           0.1.5  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + re2                        2023.02.01  hcb278e6_0               conda-forge/linux-64     Cached
  + readline                        8.1.2  h0f457ee_0               conda-forge/linux-64     Cached
  + requests                       2.28.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + requests-oauthlib               1.3.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + rich                           13.3.1  pyhd8ed1ab_1             conda-forge/noarch       Cached
  + rich-click                      1.6.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + rsa                               4.9  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + scikit-learn                    1.2.1  py310h209a8ca_0          conda-forge/linux-64     Cached
  + scipy                          1.10.0  py310h8deb116_0          conda-forge/linux-64     Cached
  + setuptools                     67.1.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + six                            1.16.0  pyh6c4a22f_0             conda-forge/noarch       Cached
  + snappy                          1.1.9  hbd366e4_2               conda-forge/linux-64     Cached
  + sqlite                         3.40.0  h4ff8645_0               conda-forge/linux-64     Cached
  + taxopy                         0.11.0  pyhdfd78af_0             bioconda/noarch          Cached
  + tensorboard                    2.11.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + tensorboard-data-server         0.6.1  py310h600f1e7_4          conda-forge/linux-64     Cached
  + tensorboard-plugin-wit          1.8.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + tensorflow                     2.11.0  cpu_py310hd1aba9c_0      conda-forge/linux-64     Cached
  + tensorflow-base                2.11.0  cpu_py310hc9b7e7f_0      conda-forge/linux-64     Cached
  + tensorflow-estimator           2.11.0  cpu_py310hfed9998_0      conda-forge/linux-64     Cached
  + termcolor                       2.2.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + threadpoolctl                   3.1.0  pyh8a188c0_0             conda-forge/noarch       Cached
  + tk                             8.6.12  h27826a3_0               conda-forge/linux-64     Cached
  + typing-extensions               4.4.0  hd8ed1ab_0               conda-forge/noarch       Cached
  + typing_extensions               4.4.0  pyha770c72_0             conda-forge/noarch       Cached
  + tzdata                          2022g  h191b570_0               conda-forge/noarch       Cached
  + urllib3                       1.26.14  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + werkzeug                        2.2.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + wget                           1.20.3  ha35d2d1_1               conda-forge/linux-64     Cached
  + wheel                          0.38.4  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + wrapt                          1.14.1  py310h5764c6d_1          conda-forge/linux-64     Cached
  + xgboost                         1.7.1  cpu_py310hd1aba9c_0      conda-forge/linux-64     Cached
  + xz                              5.2.6  h166bdaf_0               conda-forge/linux-64     Cached
  + yarl                            1.8.2  py310h5764c6d_0          conda-forge/linux-64     Cached
  + zipp                           3.12.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + zlib                           1.2.13  h166bdaf_4               conda-forge/linux-64     Cached

  Summary:

  Install: 147 packages

  Total download: 29MB

─────────────────────────────────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] y
_py-xgboost-mutex                                    7.9kB @  44.8kB/s  0.2s
cached-property                                      4.1kB @  21.0kB/s  0.2s
aria2                                               29.3MB @  38.9MB/s  0.8s

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ mamba activate genomad_env

To deactivate an active environment, use

     $ mamba deactivate

(base) [jespinoz@login02 jcl110]$ conda activate genomad_env
(genomad_env) [jespinoz@login02 jcl110]$ genomad -h
Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/site-packages/llvmlite/binding/ffi.py", line 160, in <module>
    lib = ctypes.CDLL(str(_lib_handle.__enter__()))
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libstdc++.so.6: failed to map segment from shared object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/bin/genomad", line 6, in <module>
    from genomad.cli import cli
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/site-packages/genomad/__init__.py", line 5, in <module>
    from genomad.modules import (
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/site-packages/genomad/modules/aggregated_classification.py", line 4, in <module>
    from genomad import sequence, utils
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/site-packages/genomad/sequence.py", line 9, in <module>
    from numba import njit
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/site-packages/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/site-packages/numba/core/config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/site-packages/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/expanse/projects/jcl110/anaconda3/envs/genomad_env/lib/python3.10/site-packages/llvmlite/binding/ffi.py", line 167, in <module>
    raise OSError(msg)
OSError: Could not find/load shared object file: libllvmlite.so
 Error was: libstdc++.so.6: failed to map segment from shared object
```

I got it to work by changing the llvmlite install from conda-forge to numba channel: 

```
(genomad_env) [jespinoz@login02 jcl110]$ conda install -c numba llvmlite
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /expanse/projects/jcl110/anaconda3/envs/genomad_env

  added / updated specs:
    - llvmlite


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    llvmlite-0.39.1            |  py310he1b5a44_0        28.2 MB  numba
    ------------------------------------------------------------
                                           Total:        28.2 MB

The following packages will be SUPERSEDED by a higher-priority channel:

  llvmlite           conda-forge::llvmlite-0.39.1-py310h58~ --> numba::llvmlite-0.39.1-py310he1b5a44_0


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by apcamargo** [comment]
I couldn't reproduce the bug here. I'm using mambaforge, which already includes the conda-forge channel. Maybe you are getting this error because you didn't include conda-forge in your channels?

Can you test this command?
```
mamba create -n genomad_env -c conda-forge -c bioconda genomad
```

**Comment by jolespin** [comment]
Looks like that worked.  I was assuming that it was using my conda-forge from ~/.condarc but I guess not!
