### ISSUE TITLE
mmseqs2 error

### ISSUE THREAD

**Issue by manaraleslam2018** [apcamargo/genomad#102]
Each time I run this code: genomad end-to-end --cleanup --splits 5 pump1.contigs.fa pump1_genomad_output genomad_db

I have this error:
Traceback (most recent call last):
File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/mmseqs2.py", line 190, in run_mmseqs2
subprocess.run(command, stdout=fout, stderr=fout, check=True)
File "/home/manar/apps/mamba/lib/python3.10/subprocess.py", line 526, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'prefilter', PosixPath('pump1_genomad_output/pump1.contigs_annotate/pump1.contigs_mmseqs2/query_db/query_db'), PosixPath('genomad_db/genomad_db'), PosixPath('pump1_genomad_output/pump1.contigs_annotate/pump1.contigs_mmseqs2/search_db/prefilter_db'), '--threads', '8', '-s', '4.2', '--split', '8', '--split-mode', '0', '--max-seqs', '10000000', '--min-ungapped-score', '25', '-k', '5']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/manar/apps/mamba/bin/genomad", line 8, in
sys.exit(cli())
File "/home/manar/apps/mamba/lib/python3.10/site-packages/rich_click/rich_command.py", line 367, in call
return super().call(*args, **kwargs)
File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
File "/home/manar/apps/mamba/lib/python3.10/site-packages/rich_click/rich_command.py", line 152, in main
rv = self.invoke(ctx)
File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
return f(get_current_context(), *args, **kwargs)
File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/cli.py", line 1269, in end_to_end
ctx.invoke(
File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/cli.py", line 447, in annotate
genomad.annotate.main(
File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/modules/annotate.py", line 203, in main
mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/mmseqs2.py", line 193, in run_mmseqs2
raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs prefilter pump1_genomad_output/pump1.contigs_annotate/pump1.contigs_mmseqs2/query_db/query_db genomad_db/genomad_db pump1_genomad_output/pump1.contigs_annotate/pump1.contigs_mmseqs2/search_db/prefilter_db --threads 8 -s 4.2 --split 8 --split-mode 0 --max-seqs 10000000 --min-ungapped-score 25 -k 5' failed.

Also, please find my log file:
[mmseqs2.log](https://github.com/apcamargo/genomad/files/15466537/mmseqs2.log)

**Comment by apcamargo** [comment]
This error is caused because you're using an old version of MMseqs2, which is incompatible with the geNomad database. Can you try updating to version 14?

**Comment by manaraleslam2018** [comment]
Thanks, I tried it and the problem is solved
