### ISSUE TITLE
Error mmseqs prefilter

### ISSUE THREAD

**Issue by namnh7** [apcamargo/genomad#106]
I got an error while running genomad:

[Traceback (most recent call last):
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/genomad/mmseqs2.py", line 190, in run_mmseqs2
    subprocess.run(command, stdout=fout, stderr=fout, check=True)
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'prefilter', PosixPath('2_result/genomad/C1/C1_annotate/C1_mmseqs2/query_db/query_db'), PosixPath('3_reference/genomad_db/genomad_db'), PosixPath('2_result/genomad/C1/C1_annotate/C1_mmseqs2/search_db/prefilter_db'), '--threads', '16', '-s', '4.2', '--split', '0', '--split-mode', '0', '--max-seqs', '10000000', '--min-ungapped-score', '25', '-k', '5']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/Namsp/miniconda3/envs/genomad/bin/genomad", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/genomad/cli.py", line 1269, in end_to_end
    ctx.invoke(
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/genomad/cli.py", line 447, in annotate
    genomad.annotate.main(
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/genomad/modules/annotate.py", line 203, in main
    mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
  File "/data/Namsp/miniconda3/envs/genomad/lib/python3.11/site-packages/genomad/mmseqs2.py", line 193, in run_mmseqs2
    raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs prefilter 2_result/genomad/C1/C1_annotate/C1_mmseqs2/query_db/query_db 3_reference/genomad_db/genomad_db 2_result/genomad/C1/C1_annotate/C1_mmseqs2/search_db/prefilter_db --threads 16 -s 4.2 --split 0 --split-mode 0 --max-seqs 10000000 --min-ungapped-score 25 -k 5' failed.

I'm using mmseqs version 15.6f452. Please help me!

**Comment by apcamargo** [comment]
This might be an issue with memory availability. Have you tried to increase the number of splits (e.g. `--splits 12`).
