### ISSUE TITLE
Error mmseqs prefilter 

### ISSUE THREAD

**Issue by brilliant2643** [apcamargo/genomad#113]
Hi! I'm using genomad but I come across some problems. And I don't know exactly what the problem is.
I use the commend `genomad end-to-end --cleanup --enable-score-calibration ET_1.all_1.metaspades.contigs.part_010.fasta ET_1.all_1.metaspades.contigs.part_010.genomad /home/pku-embl/workdir/genomad -t 90`

My log is like this:
╭──────────────────────────────────────────────────────────────────────────────╮
│  Executing geNomad annotate (v1.8.0). This will perform gene calling in the  │
│  input sequences and annotate the predicted proteins with geNomad's          │
│  markers.                                                                    │
│  ──────────────────────────────────────────────────────────────────────────  │
│  Outputs:                                                                    │
│    ET_1.all_1.metaspades.contigs.part_001.genomad/ET_1.all_1.metaspades.con  │
│    tigs.part_001_annotate                                                    │
│    ├── ET_1.all_1.metaspades.contigs.part_001_annotate.json (execution       │
│    │   parameters)                                                           │
│    ├── ET_1.all_1.metaspades.contigs.part_001_genes.tsv (gene annotation     │
│    │   data)                                                                 │
│    ├── ET_1.all_1.metaspades.contigs.part_001_taxonomy.tsv (taxonomic        │
│    │   assignment)                                                           │
│    ├── ET_1.all_1.metaspades.contigs.part_001_mmseqs2.tsv (MMseqs2 output    │
│    │   file)                                                                 │
│    └── ET_1.all_1.metaspades.contigs.part_001_proteins.faa (protein FASTA    │
│        file)                                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
[16:14:14] Executing genomad annotate.
[16:14:14] Creating the
           ET_1.all_1.metaspades.contigs.part_001.genomad/ET_1.all_1.metaspades.
           contigs.part_001_annotate directory.
[16:42:14] Proteins predicted with pyrodigal-gv were written to
           ET_1.all_1.metaspades.contigs.part_001_proteins.faa.
Traceback (most recent call last):
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/genomad/mmseqs2.py", line 190, in run_mmseqs2
    subprocess.run(command, stdout=fout, stderr=fout, check=True)
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'prefilter', PosixPath('ET_1.all_1.metaspades.contigs.part_001.genomad/ET_1.all_1.metaspades.contigs.part_001_annotate/ET_1.all_1.metaspades.contigs.part_001_mmseqs2/query_db/query_db'), PosixPath('/home/pku-embl/workdir/genomad/genomad_db'), PosixPath('ET_1.all_1.metaspades.contigs.part_001.genomad/ET_1.all_1.metaspades.contigs.part_001_annotate/ET_1.all_1.metaspades.contigs.part_001_mmseqs2/search_db/prefilter_db'), '--threads', '90', '-s', '4.2', '--split', '0', '--split-mode', '0', '--max-seqs', '10000000', '--min-ungapped-score', '25', '-k', '5']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pku-embl/micromamba/envs/genomad/bin/genomad", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/genomad/cli.py", line 1269, in end_to_end
    ctx.invoke(
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/genomad/cli.py", line 447, in annotate
    genomad.annotate.main(
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/genomad/modules/annotate.py", line 203, in main
    mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
  File "/home/pku-embl/micromamba/envs/genomad/lib/python3.11/site-packages/genomad/mmseqs2.py", line 193, in run_mmseqs2
    raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs prefilter ET_1.all_1.metaspades.contigs.part_001.genomad/ET_1.all_1.metaspades.contigs.part_001_annotate/ET_1.all_1.metaspades.contigs.part_001_mmseqs2/query_db/query_db /home/pku-embl/workdir/genomad/genomad_db ET_1.all_1.metaspades.contigs.part_001.genomad/ET_1.all_1.metaspades.contigs.part_001_annotate/ET_1.all_1.metaspades.contigs.part_001_mmseqs2/search_db/prefilter_db --threads 90 -s 4.2 --split 0 --split-mode 0 --max-seqs 10000000 --min-ungapped-score 25 -k 5' failed.

I tried to redownload database(version 1.7), and I also tried to use the parameter `--split 10`, but none of them worked. 
I'm wondering if there was something wrong with my environment? I used micromamba to install genomad.
And by the way my input file is 2.54GB, the server has 125G memory in total, and the version of mmseqs2 is 14.7e284

Looking forward to your reply, thanks!
Sushi

**Comment by brilliant2643** [comment]
I figured it out, the database path was wrong. It should be /home/pku-embl/workdir/genomad/genomad_db.

**Comment by apcamargo** [comment]
Good to hear you sorted this out quickly! Let me know if you have any other questions
