### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by deminatanja** [apcamargo/genomad#12]
Hi,
following my previous issue from the run with a pretty big input file, I have tried to run a much smaller assembly (the input fa.gz file is about 65 MB), but there is another error this time:
```
[14:10:19] Executing genomad annotate.
[14:10:19] Creating the ANT01_genomad_output/contigs_annotate directory.
Traceback (most recent call last):
  File "/projappl/project_2006548/genomad/bin/genomad", line 10, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/genomad/cli.py", line 1208, in end_to_end
    ctx.invoke(
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/genomad/cli.py", line 425, in annotate
    genomad.annotate.main(
  File "/opt/conda/lib/python3.10/site-packages/genomad/modules/annotate.py", line 178, in main
    prodigal_obj.run_parallel_prodigal(threads)
  File "/opt/conda/lib/python3.10/site-packages/genomad/prodigal.py", line 92, in run_parallel_prodigal
    self._append_prodigal_fasta(current_file_path, protid_start)
  File "/opt/conda/lib/python3.10/site-packages/genomad/prodigal.py", line 42, in _append_prodigal_fasta
    match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
Could you please help?
Best,
Tatiana

**Comment by apcamargo** [comment]
Sure! Can you share the file with me so I can try to replicate? This is an issue I've never seem before. Looks like a problem with the `prodigal-gv` output.

**Comment by deminatanja** [comment]
Hi,
My previous problem of having not enough disk space seems to be solved by reserving some local disk space for the temporary directory, the test run is on-going, but it has definitely already run further than the first time when the memory error appeared.
I will also test this smaller dataset with the same approach and let you know how it goes.

**Comment by deminatanja** [comment]
Update: the big dataset run completed successfully! The memory reservation for the temp dir has helped.
The smaller one is running.

**Comment by apcamargo** [comment]
Good to know :)

**Comment by deminatanja** [comment]
Update2: The smaller run has also finished without troubles. Apparently the AttributeError was also somehow due to the lack of temp dir memory reservation. The issue can be closed :)

**Comment by apcamargo** [comment]
Great! Just let me know in case you have this error again and I'll reopen it :)
