### ISSUE TITLE
run failed during annotation 

### ISSUE THREAD

**Issue by mikenada** [apcamargo/genomad#131]
Hello I recently installed genomad v1.8.0. However, when I tried to run the command, it return an error below. 

(genomadv1.8.0) dostvip2@DESKTOP-L5H6T8M:/mnt/f/Klebsiella$ genomad end-to-end 09_MOBsuite_OMCS211430/OMCS211430.fasta 11_genomad_OMCS211430 /mnt/f/Klebsiella/genomad_db --threads 6 --restart
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│  Executing geNomad annotate (v1.8.0). This will perform gene calling in the input sequences and annotate the         │
│  predicted proteins with geNomad's markers.                                                                          │
│  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│  Outputs:                                                                                                            │
│    11_genomad_OMCS211430/OMCS211430_annotate                                                                         │
│    ├── OMCS211430_annotate.json (execution parameters)                                                               │
│    ├── OMCS211430_genes.tsv (gene annotation data)                                                                   │
│    ├── OMCS211430_taxonomy.tsv (taxonomic assignment)                                                                │
│    ├── OMCS211430_mmseqs2.tsv (MMseqs2 output file)                                                                  │
│    └── OMCS211430_proteins.faa (protein FASTA file)                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[14:07:13] Executing genomad annotate.
[14:07:28] Proteins predicted with pyrodigal-gv were written to OMCS211430_proteins.faa.
Traceback (most recent call last):
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/genomad/mmseqs2.py", line 190, in run_mmseqs2
    subprocess.run(command, stdout=fout, stderr=fout, check=True)
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'prefilter', PosixPath('11_genomad_OMCS211430/OMCS211430_annotate/OMCS211430_mmseqs2/query_db/query_db'), PosixPath('/mnt/f/Klebsiella/genomad_db/genomad_db'), PosixPath('11_genomad_OMCS211430/OMCS211430_annotate/OMCS211430_mmseqs2/search_db/prefilter_db'), '--threads', '6', '-s', '4.2', '--split', '0', '--split-mode', '0', '--max-seqs', '10000000', '--min-ungapped-score', '25', '-k', '5']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/bin/genomad", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/genomad/cli.py", line 1269, in end_to_end
    ctx.invoke(
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/genomad/cli.py", line 447, in annotate
    genomad.annotate.main(
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/genomad/modules/annotate.py", line 203, in main
    mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
  File "/home/dostvip2/miniconda3/envs/genomadv1.8.0/lib/python3.11/site-packages/genomad/mmseqs2.py", line 193, in run_mmseqs2
    raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs prefilter 11_genomad_OMCS211430/OMCS211430_annotate/OMCS211430_mmseqs2/query_db/query_db /mnt/f/Klebsiella/genomad_db/genomad_db 11_genomad_OMCS211430/OMCS211430_annotate/OMCS211430_mmseqs2/search_db/prefilter_db --threads 6 -s 4.2 --split 0 --split-mode 0 --max-seqs 10000000 --min-ungapped-score 25 -k 5' failed.

**Comment by apcamargo** [comment]
This could be because you don't have enough available memory. Can you try setting `--splits 8` or even `--splits 12`? This will make the execution a bit slower, but memory requirements will reduce substantially.

**Comment by roo-weed** [comment]
Thanks for developing this excellent tool!! I think I am having a similar issue. I set `--splits 12`, but I still get the following error:
```
Traceback (most recent call last):
  File "/bioware/genomad-mamba-20230725/bin/genomad", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/genomad/cli.py", line 1213, in end_to_end
    ctx.invoke(
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/genomad/cli.py", line 425, in annotate
    genomad.annotate.main(
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/genomad/modules/annotate.py", line 202, in main
    mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
  File "/bioware/genomad-mamba-20230725/lib/python3.11/site-packages/genomad/mmseqs2.py", line 140, in run_mmseqs2
    raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs search 09_VIRALID/genomad/genomad_output_viral_coassembly/final.contigs.final_header_annotate/final.contigs.final_header_mmseqs2/query_db/query_db /workspace/rweed/TR_phage_redo/genomad_db/genomad_db 09_VIRALID/genomad/genomad_output_viral_coassembly/final.contigs.final_header_annotate/final.contigs.final_header_mmseqs2/search_db/search_db 09_VIRALID/genomad/genomad_output_viral_coassembly/final.contigs.final_header_annotate/final.contigs.final_header_mmseqs2/tmp --threads 40 -s 4.2 --cov-mode 1 -c 0.2 -e 0.001 --split 12 --split-mode 0 --max-seqs 1000000 --min-ungapped-score 20 --max-rejected 225' failed.
```
It is possible that mmseqs2 has been updated since I last ran geNomad (which has always worked beautifully for me on the same machine with the same settings). I would appreciate any advice you have!
-Roo

**Comment by apcamargo** [comment]
Hi @roo-weed,

I've tested the new version of MMseqs2 and had no issue. Can you try running your data with both version 16 and 15 and tell me if it works if you downgrade to 15?

**Comment by WUD2018** [comment]
Hey developer,

I also run into a similar problem: 

╭──────────────────────────────────────────────────────────────────────────────╮
│  Executing geNomad annotate (v1.11.0). This will perform gene calling in     │
│  the input sequences and annotate the predicted proteins with geNomad's      │
│  markers.                                                                    │
│  ──────────────────────────────────────────────────────────────────────────  │
│  Outputs:                                                                    │
│    genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate                │
│    ├── GCA_000153245.1_ASM15324v1_genomic_annotate.json (execution           │
│    │   parameters)                                                           │
│    ├── GCA_000153245.1_ASM15324v1_genomic_genes.tsv (gene annotation data)   │
│    ├── GCA_000153245.1_ASM15324v1_genomic_taxonomy.tsv (taxonomic            │
│    │   assignment)                                                           │
│    ├── GCA_000153245.1_ASM15324v1_genomic_mmseqs2.tsv (MMseqs2 output file)  │
│    └── GCA_000153245.1_ASM15324v1_genomic_proteins.faa (protein FASTA file)  │
╰──────────────────────────────────────────────────────────────────────────────╯
[10:43:22] Executing genomad annotate.                                          
[10:43:22] Previous execution detected. Steps will be skipped unless their      
           outputs are not found. Use the --restart option to force the         
           execution of all the steps again.                                    
[10:43:22] GCA_000153245.1_ASM15324v1_genomic_proteins.faa was found. Skipping  
           gene prediction with pyrodigal-gv.                                   
Traceback (most recent call last):
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/mmseqs2.py", line 190, in run_mmseqs2
    subprocess.run(command, stdout=fout, stderr=fout, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'prefilter', PosixPath('genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate/GCA_000153245.1_ASM15324v1_genomic_mmseqs2/query_db/query_db'), PosixPath('/home/dell/Database/GenoMAD/genomad_db/genomad_db'), PosixPath('genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate/GCA_000153245.1_ASM15324v1_genomic_mmseqs2/search_db/prefilter_db'), '--threads', '256', '-s', '4.2', '--split', '8', '--split-mode', '0', '--max-seqs', '10000000', '--min-ungapped-score', '25', '-k', '5']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dell/.local/bin/genomad", line 8, in <module>
    sys.exit(cli())
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/rich_click/rich_command.py", line 378, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/rich_click/rich_command.py", line 166, in main
    rv = self.invoke(ctx)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 1329, in end_to_end
    ctx.invoke(
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 468, in annotate
    genomad.annotate.main(
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/modules/annotate.py", line 204, in main
    mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/mmseqs2.py", line 193, in run_mmseqs2
    raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs prefilter genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate/GCA_000153245.1_ASM15324v1_genomic_mmseqs2/query_db/query_db /home/dell/Database/GenoMAD/genomad_db/genomad_db genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate/GCA_000153245.1_ASM15324v1_genomic_mmseqs2/search_db/prefilter_db --threads 256 -s 4.2 --split 8 --split-mode 0 --max-seqs 10000000 --min-ungapped-score 25 -k 5' failed.



I have check my conda list. The mmseq2 is above v15




# packages in environment at /home/dell/anaconda3/envs/genomad:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
aragorn                   1.2.41               h7b50bb2_5    https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda
argcomplete               1.12.3             pyhd3eb1b0_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
aria2                     1.37.0               hbc8128a_2    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
bzip2                     1.0.8                h5eee18b_6    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
c-ares                    1.34.4               hb9d3cd8_0    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2025.2.25            h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
click                     8.1.7           py313h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
colorama                  0.4.6           py313h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
gawk                      5.3.1                h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
icu                       75.1                 he02047a_0    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
importlib-metadata        2.0.0                      py_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
importlib_metadata        2.0.0                         1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
ld_impl_linux-64          2.40                 h12ee557_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libexpat                  2.6.4                h5888daf_0    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.4                h6a678d5_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libgcc                    14.2.0               h767d61c_2    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 14.2.0               h69a702a_2    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libgomp                   14.2.0               h767d61c_2    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.18                 h4ce23a2_1    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
liblzma                   5.6.4                hb9d3cd8_0    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libmpdec                  4.0.0                h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
libsqlite                 3.49.1               hee588c1_1    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libssh2                   1.11.1               hf672d98_0    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libstdcxx                 14.2.0               h8f9b012_2    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              14.2.0               h4852527_2    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.38.1               h0b41bf4_0    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.13.6               h8d12d68_0    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.3.1                hb9d3cd8_2    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
mmseqs2                   17.b804f             hd6d6fdc_1    https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda
ncurses                   6.5                  h2d0b736_3    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
openssl                   3.4.1                h7b32b05_0    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
packaging                 24.2            py313h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
pip                       25.0            py313h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
pipx                      1.7.1              pyhd8ed1ab_1    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
platformdirs              3.10.0          py313h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
python                    3.13.2          hf636f53_101_cp313    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
python_abi                3.13                    0_cp313    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
readline                  8.2                  h5eee18b_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
setuptools                75.8.0          py313h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
tk                        8.6.13          noxft_h4845f30_101    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
tomli                     2.0.1           py313h06a4308_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
tzdata                    2025a                h04d1e81_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
userpath                  1.9.2              pyhd8ed1ab_0    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
wheel                     0.45.1          py313h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
zipp                      3.21.0          py313h06a4308_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
zlib                      1.3.1                hb9d3cd8_2    https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge

**Comment by apcamargo** [comment]
@WUD2018 can you try to run with `--splits 12`? Just to make sure the issue is not insufficient memory.

**Comment by WUD2018** [comment]
> [@WUD2018](https://github.com/WUD2018) can you try to run with `--splits 12`? Just to make sure the issue is not insufficient memory.

I have tried, but it still shows:

╭──────────────────────────────────────────────────────────────────────────────╮
│  Executing geNomad annotate (v1.11.0). This will perform gene calling in     │
│  the input sequences and annotate the predicted proteins with geNomad's      │
│  markers.                                                                    │
│  ──────────────────────────────────────────────────────────────────────────  │
│  Outputs:                                                                    │
│    genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate                │
│    ├── GCA_000153245.1_ASM15324v1_genomic_annotate.json (execution           │
│    │   parameters)                                                           │
│    ├── GCA_000153245.1_ASM15324v1_genomic_genes.tsv (gene annotation data)   │
│    ├── GCA_000153245.1_ASM15324v1_genomic_taxonomy.tsv (taxonomic            │
│    │   assignment)                                                           │
│    ├── GCA_000153245.1_ASM15324v1_genomic_mmseqs2.tsv (MMseqs2 output file)  │
│    └── GCA_000153245.1_ASM15324v1_genomic_proteins.faa (protein FASTA file)  │
╰──────────────────────────────────────────────────────────────────────────────╯
[10:55:10] Executing genomad annotate.                                          
[10:55:10] Creating the                                                         
           genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate directory.
[10:55:14] Proteins predicted with pyrodigal-gv were written to                 
           GCA_000153245.1_ASM15324v1_genomic_proteins.faa.                     
Traceback (most recent call last):
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/mmseqs2.py", line 190, in run_mmseqs2
    subprocess.run(command, stdout=fout, stderr=fout, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'prefilter', PosixPath('genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate/GCA_000153245.1_ASM15324v1_genomic_mmseqs2/query_db/query_db'), PosixPath('/home/dell/Database/GenoMAD/genomad_db/genomad_db'), PosixPath('genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate/GCA_000153245.1_ASM15324v1_genomic_mmseqs2/search_db/prefilter_db'), '--threads', '256', '-s', '4.2', '--split', '12', '--split-mode', '0', '--max-seqs', '10000000', '--min-ungapped-score', '25', '-k', '5']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dell/.local/bin/genomad", line 8, in <module>
    sys.exit(cli())
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/rich_click/rich_command.py", line 378, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/rich_click/rich_command.py", line 166, in main
    rv = self.invoke(ctx)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 1329, in end_to_end
    ctx.invoke(
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 468, in annotate
    genomad.annotate.main(
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/modules/annotate.py", line 204, in main
    mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
  File "/home/dell/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/mmseqs2.py", line 193, in run_mmseqs2
    raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs prefilter genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate/GCA_000153245.1_ASM15324v1_genomic_mmseqs2/query_db/query_db /home/dell/Database/GenoMAD/genomad_db/genomad_db genomad_output/GCA_000153245.1_ASM15324v1_genomic_annotate/GCA_000153245.1_ASM15324v1_genomic_mmseqs2/search_db/prefilter_db --threads 256 -s 4.2 --split 12 --split-mode 0 --max-seqs 10000000 --min-ungapped-score 25 -k 5' failed.
