### ISSUE TITLE
Issues running genomad

### ISSUE THREAD

**Issue by david1ibarra** [apcamargo/genomad#43]
genomad end-to-end --cleanup --splits 8 "/mnt/c/Users/DavidIbarra/OneDrive - Cemvita Factory Inc/Desktop/GCF001999325.1.fasta" genomad_output "/mnt/c/Users/DavidIbarra/genomad_db"
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│  Executing geNomad annotate (v1.7.0). This will perform gene calling in the input sequences and annotate the predicted   │
│  proteins with geNomad's markers.                                                                                        │
│  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│  Outputs:                                                                                                                │
│    genomad_output/GCF001999325.1_annotate                                                                                │
│    ├── GCF001999325.1_annotate.json (execution parameters)                                                               │
│    ├── GCF001999325.1_genes.tsv (gene annotation data)                                                                   │
│    ├── GCF001999325.1_taxonomy.tsv (taxonomic assignment)                                                                │
│    ├── GCF001999325.1_mmseqs2.tsv (MMseqs2 output file)                                                                  │
│    └── GCF001999325.1_proteins.faa (protein FASTA file)                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[13:50:35] Executing genomad annotate.
[13:50:35] Previous execution detected. Steps will be skipped unless their outputs are not found. Use the --restart option
           to force the execution of all the steps again.
[13:50:35] GCF001999325.1_proteins.faa was found. Skipping gene prediction with prodigal-gv.
Traceback (most recent call last):
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/mmseqs2.py", line 190, in run_mmseqs2
    subprocess.run(command, stdout=fout, stderr=fout, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'prefilter', PosixPath('genomad_output/GCF001999325.1_annotate/GCF001999325.1_mmseqs2/query_db/query_db'), PosixPath('/mnt/c/Users/DavidIbarra/genomad_db/genomad_db'), PosixPath('genomad_output/GCF001999325.1_annotate/GCF001999325.1_mmseqs2/search_db/prefilter_db'), '--threads', '12', '-s', '4.2', '--split', '8', '--split-mode', '0', '--max-seqs', '10000000', '--min-ungapped-score', '25', '-k', '5']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/david1ibarra/.local/bin/genomad", line 8, in <module>
    sys.exit(cli())
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 1240, in end_to_end
    ctx.invoke(
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 441, in annotate
    genomad.annotate.main(
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/modules/annotate.py", line 203, in main
    mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
  File "/home/david1ibarra/.local/pipx/venvs/genomad/lib/python3.10/site-packages/genomad/mmseqs2.py", line 193, in run_mmseqs2
    raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs prefilter genomad_output/GCF001999325.1_annotate/GCF001999325.1_mmseqs2/query_db/query_db /mnt/c/Users/DavidIbarra/genomad_db/genomad_db genomad_output/GCF001999325.1_annotate/GCF001999325.1_mmseqs2/search_db/prefilter_db --threads 12 -s 4.2 --split 8 --split-mode 0 --max-seqs 10000000 --min-ungapped-score 25 -k 5' failed.

Not sure what went wrong or how to fix

**Comment by apcamargo** [comment]
It seems that mmseqs2 failed. You can try to increase the number of splits (e.g. `--splits 12`).

Can you send me the contents of `genomad_output/GCF001999325.1_annotate/GCF001999325.1_mmseqs2/mmseqs2.log`?
