### ISSUE TITLE
Error running Genomad 1.7.1

### ISSUE THREAD

**Issue by mhmism** [apcamargo/genomad#50]
Version 1.6.1 worked fine for me. 

After installing Genomad 1.7.1 (fresh install), I get the following error: 

Traceback (most recent call last):
  File "/gpfs/work5/0/gusr0570/conda/genomad_1.7.1/bin/genomad", line 6, in <module>
    from genomad.cli import cli
  File "/gpfs/work5/0/gusr0570/conda/genomad_1.7.1/lib/python3.10/site-packages/genomad/__init__.py", line 5, in <module>
    from genomad.modules import (
  File "/gpfs/work5/0/gusr0570/conda/genomad_1.7.1/lib/python3.10/site-packages/genomad/modules/annotate.py", line 4, in <module>
    from genomad import database, mmseqs2, prodigal, sequence, taxonomy, utils
  File "/gpfs/work5/0/gusr0570/conda/genomad_1.7.1/lib/python3.10/site-packages/genomad/prodigal.py", line 5, in <module>
    import pyrodigal_gv
  File "/gpfs/work5/0/gusr0570/conda/genomad_1.7.1/lib/python3.10/site-packages/pyrodigal_gv/__init__.py", line 11, in <module>
    from .meta import METAGENOMIC_BINS, METAGENOMIC_BINS_VIRAL
  File "/gpfs/work5/0/gusr0570/conda/genomad_1.7.1/lib/python3.10/site-packages/pyrodigal_gv/meta.py", line 12, in <module>
    METAGENOMIC_BINS = pyrodigal.MetagenomicBins([
AttributeError: module 'pyrodigal' has no attribute 'MetagenomicBins'. Did you mean: 'MetagenomicBin'?

**Comment by apcamargo** [comment]
The issue you're experiencing does not appear to be a bug with geNomad. It seems that an outdated version of pyrodigal was installed instead. You need to ensure that you have pyrodigal version 3.1.0 or higher, which should have been installed automatically. Could you please tell me how you installed geNomad?

To resolve this issue, you should attempt to update pyrodigal.

**Comment by mhmism** [comment]
I tried version 1.7.0 and it works, but there is a problem with 1.7.1.

I installed it with conda. I think I also checked the pyridogal version and it is up-to-date. It could be a conflict in my own environment that needs further investigation. 

For now, I am happy with version 1.7.0 until the next major update.
