### ISSUE TITLE
error with end-to-end

### ISSUE THREAD

**Issue by abdo3a** [apcamargo/genomad#53]
Hello, i'm trying to run this command:
genomad  end-to-end MEGAHIT-group-Box_D1.contigs.fa ./  genomad_db --threads 50    --cleanup --min-score 0.7 --splits 1

with geNomad, version 1.7.1 and MMseqs2 Version: 14.7e284

but, got the following error:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/genomad", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/genomad/cli.py", line 1213, in end_to_end
    ctx.invoke(
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/genomad/cli.py", line 425, in annotate
    genomad.annotate.main(
  File "/usr/local/lib/python3.10/site-packages/genomad/modules/annotate.py", line 202, in main
    mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
  File "/usr/local/lib/python3.10/site-packages/genomad/mmseqs2.py", line 140, in run_mmseqs2
    raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs search MEGAHIT-group-Box_D1.contigs_annotate/MEGAHIT-group-Box_D1.contigs_mmseqs2/query_db/query_db genomad_db/genomad_db MEGAHIT-group-Box_D1.contigs_annotate/MEGAHIT-group-Box_D1.contigs_mmseqs2/search_db/search_db MEGAHIT-group-Box_D1.contigs_annotate/MEGAHIT-group-Box_D1.contigs_mmseqs2/tmp --threads 50 -s 4.2 --cov-mode 1 -c 0.2 -e 0.001 --split 1 --split-mode 0 --max-seqs 1000000 --min-ungapped-score 20 --max-rejected 225' failed.

**Comment by apcamargo** [comment]
Can you provide the contents of the log file inside `<prefix>_annotate/mmseqs2`?

**Comment by abdo3a** [comment]
thanks @apcamargo , here is the mmseq2 log file.
[mmseqs2.log](https://github.com/apcamargo/genomad/files/13402781/mmseqs2.log)

**Comment by apcamargo** [comment]
It seems the prefilter step of the mmseqs2 search died. Likely to lack of memory.

Can you try setting `--splits 12`? See [here](https://portal.nersc.gov/genomad/quickstart.html#notes-about-parameters) an explanation.

**Comment by manaraleslam2018** [comment]
I have a similar problem, this the error I have each time I run: genomad end-to-end --cleanup --splits 5 pump1.contigs.fa pump1_genomad_output genomad_db

Traceback (most recent call last):
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/mmseqs2.py", line 190, in run_mmseqs2
    subprocess.run(command, stdout=fout, stderr=fout, check=True)
  File "/home/manar/apps/mamba/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'prefilter', PosixPath('pump1_genomad_output/pump1.contigs_annotate/pump1.contigs_mmseqs2/query_db/query_db'), PosixPath('genomad_db/genomad_db'), PosixPath('pump1_genomad_output/pump1.contigs_annotate/pump1.contigs_mmseqs2/search_db/prefilter_db'), '--threads', '8', '-s', '4.2', '--split', '8', '--split-mode', '0', '--max-seqs', '10000000', '--min-ungapped-score', '25', '-k', '5']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/manar/apps/mamba/bin/genomad", line 8, in <module>
    sys.exit(cli())
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/cli.py", line 1269, in end_to_end
    ctx.invoke(
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/cli.py", line 447, in annotate
    genomad.annotate.main(
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/modules/annotate.py", line 203, in main
    mmseqs2_obj.run_mmseqs2(threads, sensitivity, evalue, splits)
  File "/home/manar/apps/mamba/lib/python3.10/site-packages/genomad/mmseqs2.py", line 193, in run_mmseqs2
    raise Exception(f"'{command_str}' failed.") from e
Exception: 'mmseqs prefilter pump1_genomad_output/pump1.contigs_annotate/pump1.contigs_mmseqs2/query_db/query_db genomad_db/genomad_db pump1_genomad_output/pump1.contigs_annotate/pump1.contigs_mmseqs2/search_db/prefilter_db --threads 8 -s 4.2 --split 8 --split-mode 0 --max-seqs 10000000 --min-ungapped-score 25 -k 5' failed.
   
Also, please find my log file:
[mmseqs2.log](https://github.com/apcamargo/genomad/files/15466510/mmseqs2.log)

**Comment by apcamargo** [comment]
This error is caused because you're using an old version of MMseqs2, which is incompatible with the geNomad database. Can you try updating to version 14?
