### ISSUE TITLE
undefined symbol error in end-to-end pipeline

### ISSUE THREAD

**Issue by DOieGYuan** [apcamargo/genomad#65]
Hi. Dear developer. Thank you for making this awesome tool!
I use Genomad to annotate metagenomic assemble (i.e., contigs) using the end-to-end pipeline. When the message "geNomad marker-classification finished!" shows up, I get the error message as follows,
Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/virus/bin/genomad", line 10, in <module>
    sys.exit(cli())
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/genomad/cli.py", line 1276, in end_to_end
    ctx.invoke(
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/genomad/cli.py", line 719, in nn_classification
    genomad.nn_classification.main(
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/genomad/modules/nn_classification.py", line 35, in main
    import tensorflow as tf
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/__init__.py", line 48, in <module>
    from tensorflow._api.v2 import __internal__
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/python/autograph/core/ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/python/autograph/utils/__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/python/autograph/utils/context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 34, in <module>
    self_check.preload_check()
  File "/home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/python/platform/self_check.py", line 63, in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard
ImportError: /home/nature/anaconda3/envs/virus/lib/python3.10/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2: undefined symbol: _ZTIN6snappy4SinkE

Could you help me figure out what is the problem? Thank you so much.

Sincerely, 

DOieGYuan

**Comment by apcamargo** [comment]
Hi @DOieGYuan 

Can you check which version of TensorFlow and Keri's you have installed?

**Comment by DOieGYuan** [comment]
> Hi @DOieGYuan
> 
> Can you check which version of TensorFlow and Keri's you have installed?

Hi @apcamargo.
Thank you for you reply.
I follow the instructions to install Genomad using mamba in the user guide. The TensorFlow is v2.15.0. And I'm not sure whether Keri's is installed because I only see keras (v2.15.0) in the conda environment. 

Follows are the results of `conda list`:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
absl-py                   2.0.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
aragorn                   1.2.41               h031d066_1    bioconda
archspec                  0.2.2              pyhd8ed1ab_0    conda-forge
aria2                     1.37.0               h347180d_1    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
blas                      1.1                    openblas    conda-forge
blinker                   1.7.0              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                    pypi_0    pypi
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.24.0               hd590300_0    conda-forge
ca-certificates           2023.12.12           h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.2              pyhd8ed1ab_0    conda-forge
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7                    pypi_0    pypi
cryptography              41.0.7                   pypi_0    pypi
flatbuffers               23.5.26              h59595ed_1    conda-forge
frozenlist                1.4.1                    pypi_0    pypi
gast                      0.5.4              pyhd8ed1ab_0    conda-forge
gawk                      5.3.0                ha916aea_0    conda-forge
genomad                   1.7.4              pyhdfd78af_0    bioconda
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h5eee18b_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gmp                       6.3.0                h59595ed_0    conda-forge
google-auth               2.25.2             pyhca7485f_0    conda-forge
google-auth-oauthlib      1.2.0              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
grpcio                    1.59.3                   pypi_0    pypi
h5py                      3.10.0                   pypi_0    pypi
hdf5                      1.14.3          nompi_h4f84152_100    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
keras                     2.15.0             pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libedit                   3.1.20230828         h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.4                h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libgrpc                   1.59.3               hd6c4280_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               4.24.4               hf27288f_0    conda-forge
libre2-11                 2023.06.02           h7a70373_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libunistring              0.9.10               h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxgboost                2.0.3            cpu_h6728c87_0    conda-forge
libxml2                   2.12.3               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.41.1                   pypi_0    pypi
markdown                  3.5.1              pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3                    pypi_0    pypi
mdurl                     0.1.0                    pypi_0    pypi
ml-dtypes                 0.2.0                    pypi_0    pypi
ml_dtypes                 0.2.0           py310hcc13569_2    conda-forge
mmseqs2                   14.7e284        pl5321h6a68c12_2    bioconda
mpfr                      4.2.1                h9458935_0    conda-forge
multidict                 6.0.4                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    conda-forge
numba                     0.58.1                   pypi_0    pypi
numpy                     1.26.2                   pypi_0    pypi
numpy-base                1.26.2          py310h8a23956_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
oauthlib                  3.2.2                    pypi_0    pypi
openblas                  0.3.25          pthreads_h7a3da1a_0    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
opt_einsum                3.3.0              pyhc1e730c_2    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
protobuf                  4.24.4                   pypi_0    pypi
py-xgboost                2.0.3           cpu_py310h78d450f_0    conda-forge
pyasn1                    0.5.1              pyhd8ed1ab_0    conda-forge
pyasn1-modules            0.3.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.3.0             pyhd8ed1ab_0    conda-forge
pyrodigal                 3.2.1                    pypi_0    pypi
pyrodigal-gv              0.3.1              pyh7cba7a3_0    bioconda
pysocks                   1.7.1                    pypi_0    pypi
python                    3.10.13         hd12c33a_1_cpython    conda-forge
python-crfsuite           0.9.9                    pypi_0    pypi
python-flatbuffers        23.5.26            pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
re2                       2023.06.02           h2873b5e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rich                      13.7.0             pyhd8ed1ab_0    conda-forge
rich-click                1.7.2              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
setuptools                68.2.2                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
snappy                    1.1.10               h6a678d5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
taxopy                    0.12.0             pyhdfd78af_0    bioconda
tensorboard               2.15.1             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorflow                2.15.0                   pypi_0    pypi
tensorflow-base           2.15.0          cpu_py310h7e4d085_1    conda-forge
tensorflow-estimator      2.15.0                   pypi_0    pypi
termcolor                 2.3.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
urllib3                   1.26.18                  pypi_0    pypi
werkzeug                  3.0.1              pyhd8ed1ab_0    conda-forge
wget                      1.21.4               h251f7ec_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wrapt                     1.14.1                   pypi_0    pypi
xgboost                   2.0.3                    pypi_0    pypi
xz                        5.4.5                h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yarl                      1.9.3                    pypi_0    pypi
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge

**Comment by apcamargo** [comment]
I meant Keras, that was a typo.

I couldn't reproduce the issue. Can you delete the environment and install everything again?

```
 mamba remove --all -n genomad
mamba clean --all
```

**Comment by DOieGYuan** [comment]
> I meant Keras, that was a typo.
> 
> I couldn't reproduce the issue. Can you delete the environment and install everything again?
> 
> ```
>  mamba remove --all -n genomad
> mamba clean --all
> ```

Hi apcamargo. I tried but encountered the same issue.
The command I used was `genomad end-to-end --cleanup --splits 4 test.fa genomad_test Genomad_db`
And the fasta file is [test.zip](https://github.com/apcamargo/genomad/files/13809965/test.zip)

**Comment by DOieGYuan** [comment]
> I meant Keras, that was a typo.
> 
> I couldn't reproduce the issue. Can you delete the environment and install everything again?
> 
> ```
>  mamba remove --all -n genomad
> mamba clean --all
> ```

Hi apcamargo. I tried but encountered the same issue.
The command I used was `genomad end-to-end --cleanup --splits 4 test.fa genomad_test Genomad_db`
And the fasta file is [test.zip](https://github.com/apcamargo/genomad/files/13809965/test.zip)

**Comment by apcamargo** [comment]
Thanks for providing the FASTA file.

I couldn't reproduce the bug, I tested different TensorFlow/Keras versions. Do you have a GPU in the computer you're trying to run geNomad on?
