### ISSUE TITLE
Errors when download and the same issue when running genomad -h

### ISSUE THREAD

**Issue by Tsingsjeen** [apcamargo/genomad#98]
(base) alex_chen@shpc-3535-instance-jBqE8J6O:~/database/GENOMAD_DB$ genomad download-database .
Traceback (most recent call last):
  File "/home/alex_chen/miniconda3/bin/genomad", line 6, in <module>
    from genomad.cli import cli
  File "/home/alex_chen/miniconda3/lib/python3.10/site-packages/genomad/__init__.py", line 5, in <module>
    from genomad.modules import (
  File "/home/alex_chen/miniconda3/lib/python3.10/site-packages/genomad/modules/marker_classification.py", line 15, in <module>
    np.warnings.filterwarnings("ignore", "overflow")
  File "/home/alex_chen/miniconda3/lib/python3.10/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'. Did you mean: 'hanning'?

thank you!

**Comment by apcamargo** [comment]
Hi @Tsingsjeen,

This bug was fixed in version 1.6.1. Can you try updating your installation to the latest geNomad version (right now, version 1.8.0)? This should fix your issue.

**Comment by Tsingsjeen** [comment]
@apcamargo , thanks! now solved!

**Comment by apcamargo** [comment]
Good to hear!! Let me know if you need further help.
